### ISSUE TITLE
You need help?

### ISSUE THREAD

**Issue by lopestom** [iamsj7/android_device_blackview_tab10pro_twrp#1]
> .... can you drop your telegram id. i need to discusss about something related to MT8778

I'll help you in your repository. If you want help so go to repository and place Colaborator with by my avatar.
But about encryption/decryption it is something you will have to learn and test for yourself on the device.

Write about specs of the device here or on the repository Readme file. Ah! if device is https://www.gsmarena.com/blackview_tab_10_pro-11591.php so only confirm.

**Comment by iamsj7** [comment]
@lopestom share your telegram

**Comment by lopestom** [comment]
> @lopestom share your telegram

I don't have : )

**Comment by iamsj7** [comment]
@lopestom how we can connect :)

**Comment by iamsj7** [comment]
I can verify that the device is indeed the one you mentioned: [Blackview Tab 10 Pro](https://www.gsmarena.com/blackview_tab_10_pro-11591.php). Additionally, I have included you as a collaborator in this repository. Please feel free to submit a pull request with your changes.

Furthermore, I'm currently running Android 13 with the Pixel Experience GSI on it.

**Comment by lopestom** [comment]
> I can verify that the device is indeed the one you mentioned: [Blackview Tab 10 Pro](https://www.gsmarena.com/blackview_tab_10_pro-11591.php). Additionally, I have included you as a collaborator in this repository. Please feel free to submit a pull request with your changes.
> 
> Furthermore, I'm currently running Android 13 with the Pixel Experience GSI on it.

I need recovery.img/boot.img (if have) from stock ROM.
But if you can put link to same firmware version that have in your device so it's better.

Go to fastboot mode: `fastboot getvar all`

Go to fastboot**D** mode: `fastboot getvar all`

copy to any txt file and send me.

**Comment by gaith-cr** [comment]
> > I can verify that the device is indeed the one you mentioned: [Blackview Tab 10 Pro](https://www.gsmarena.com/blackview_tab_10_pro-11591.php). Additionally, I have included you as a collaborator in this repository. Please feel free to submit a pull request with your changes.
> > Furthermore, I'm currently running Android 13 with the Pixel Experience GSI on it.
> 
> I need recovery.img/boot.img (if have) from stock ROM. But if you can put link to same firmware version that have in your device so it's better.
> 
> Go to fastboot mode: `fastboot getvar all`
> 
> Go to fastboot**D** mode: `fastboot getvar all`
> 
> copy to any txt file and send me 
my stock rom link:https://mega.nz/file/KSJm1JCC#vo0h2EuCokuzoQEJLRW4UI7xGLTUyKaKRE5VhU4eAeY

however there is a shortcut to the stock boot.img:https://mega.nz/file/yMF30RAC#bvsFZURHc8YY3Dnw9__3tbKCoy1JPcZOFJPTYIvhb5Q

**Comment by lopestom** [comment]
> > > I can verify that the device is indeed the one you mentioned: [Blackview Tab 10 Pro](https://www.gsmarena.com/blackview_tab_10_pro-11591.php). Additionally, I have included you as a collaborator in this repository. Please feel free to submit a pull request with your changes.
> > > Furthermore, I'm currently running Android 13 with the Pixel Experience GSI on it.
> > 
> > 
> > I need recovery.img/boot.img (if have) from stock ROM. But if you can put link to same firmware version that have in your device so it's better.
> > Go to fastboot mode: `fastboot getvar all`
> > Go to fastboot**D** mode: `fastboot getvar all`
> > copy to any txt file and send me
> 
> my stock rom link:https://mega.nz/file/KSJm1JCC#vo0h2EuCokuzoQEJLRW4UI7xGLTUyKaKRE5VhU4eAeY
> 
> however there is a shortcut to the stock boot.img:https://mega.nz/file/yMF30RAC#bvsFZURHc8YY3Dnw9__3tbKCoy1JPcZOFJPTYIvhb5Q
> 
> pls i have been trying to build twarp for the device for the past 2 months if u help i will appreciate ur work

Tab10Pro_NEU_TP716_V1.0_20220803V05.zip

NEU model is not good to have TWRP. Maybe RU or GL (Global) is better.
But I can try because @iamsj7 not linked stock ROM yet. I not promisse TWRP working!
vasilashyk from 4pda is you?

**Comment by gaith-cr** [comment]
> no he is the blackview customer service who give the stock rom (I think) _idk what ur talking about but i responded anyway_

after google searching i realized that u mean the ru guy on that website (how ever: no im not him)

**Comment by gaith-cr** [comment]
> > no he is the blackview customer service who give the stock rom (I think) _idk what ur talking about but i responded anyway_
> 
> after google searching i realized that u mean the ru guy on that website (how ever: no im not him)

if u can to send him the stock firmware link that would be nice of u too
 (i struggled to get the customer service to give the stock rom for some reasons but there is a guy who had enough of me and gave it to me)

**Comment by lopestom** [comment]
> after google searching i realized that u mean the ru guy on that website (how ever: no im not him)

Go to fastboot mode: `fastboot getvar all`
Go to fastbootD mode: `fastboot getvar all`
copy to any txt file and send me

If you can try too: `adb shell getprop`

**Comment by lopestom** [comment]
> > > no he is the blackview customer service who give the stock rom (I think) _idk what ur talking about but i responded anyway_
> > 
> > 
> > after google searching i realized that u mean the ru guy on that website (how ever: no im not him)
> 
> if u can to send him the stock firmware link that would be nice of u too (i struggled to get the customer service to give the stock rom for some reasons but there is a guy who had enough of me and gave it to me)

https://4pda.to/forum/index.php?showtopic=1040158&view=findpost&p=117592657

**Comment by iamsj7** [comment]
I got this firmware  from customer service.

The latest version is Tab10Pro_NEU_TP716_V1.0_20220803V05

https://mega.nz/file/KSJm1JCC#vo0h2EuCokuzoQEJLRW4UI7xGLTUyKaKRE5VhU4eAeY

tool: https://mega.nz/file/nHZnSJ7K#1q5GcFY8GJFVB4DRzkO1vi7azR5RC5809cHRwPd20Ds

driver: https://mega.nz/file/XCIWQYyL#KfRQmHtnMRkMQ8-i0ijgspWSyDbs_NLsjvKGnmagbl8

**Comment by gaith-cr** [comment]
thats the same as me????

**Comment by gaith-cr** [comment]
> > after google searching i realized that u mean the ru guy on that website (how ever: no im not him)
> 
> Go to fastboot mode: `fastboot getvar all` Go to fastbootD mode: `fastboot getvar all` copy to any txt file and send me
> 
> If you can try too: `adb shell getprop`

anyway . i didnt know that u need anything with actual device since im far from home (i hope that u wait me until Sunday or Monday)

**Comment by lopestom** [comment]
> I got this firmware from customer service.
> 
> The latest version is Tab10Pro_NEU_TP716_V1.0_20220803V05
> 
> https://mega.nz/file/KSJm1JCC#vo0h2EuCokuzoQEJLRW4UI7xGLTUyKaKRE5VhU4eAeY
> 
> tool: https://mega.nz/file/nHZnSJ7K#1q5GcFY8GJFVB4DRzkO1vi7azR5RC5809cHRwPd20Ds
> 
> driver: https://mega.nz/file/XCIWQYyL#KfRQmHtnMRkMQ8-i0ijgspWSyDbs_NLsjvKGnmagbl8

@iamsj7 
Same by this https://github.com/iamsj7/android_device_blackview_tab10pro_twrp/issues/1#issuecomment-1708671473

**Comment by gaith-cr** [comment]
@iamsj7 since u have my same device I WILL BE COUNTING ON YOU!

**Comment by iamsj7** [comment]
> > I got this firmware from customer service.
> > The latest version is Tab10Pro_NEU_TP716_V1.0_20220803V05
> > https://mega.nz/file/KSJm1JCC#vo0h2EuCokuzoQEJLRW4UI7xGLTUyKaKRE5VhU4eAeY
> > tool: https://mega.nz/file/nHZnSJ7K#1q5GcFY8GJFVB4DRzkO1vi7azR5RC5809cHRwPd20Ds
> > driver: https://mega.nz/file/XCIWQYyL#KfRQmHtnMRkMQ8-i0ijgspWSyDbs_NLsjvKGnmagbl8
> 
> @iamsj7 Same by this [#1 (comment)](https://github.com/iamsj7/android_device_blackview_tab10pro_twrp/issues/1#issuecomment-1708671473)
> 
> @gaith-cr Time is not mine.... I have patience.... Maybe iamsj7 can make that.

Why its's not good to have TWRP ?

**Comment by iamsj7** [comment]
@gaith-cr I just started to sync the sources, let's give it a try.

**Comment by iamsj7** [comment]
@lopestom just link me any twrp which is close to this MTK8768

**Comment by lopestom** [comment]
@iamsj7 
I'm waiting this https://github.com/iamsj7/android_device_blackview_tab10pro_twrp/issues/1#issuecomment-1708753011

**Comment by gaith-cr** [comment]
@iamsj7 Any updates?

**Comment by gaith-cr** [comment]
@lopestom from where i can get the boot_Tab10Pro_A11-20230908.img?

and the twarp u placed its link to a zip file and not (twarp).img

or maybe i just dont know how things work if is so
tell me what i should do

**Comment by lopestom** [comment]
> @lopestom from where i can get the boot_Tab10Pro_A11-20230908.img?
> 
> and the twarp u placed its link to a zip file and not (twarp).img
> 
> or maybe i just dont know how things work if is so tell me what i should do
> 
> if u can give me instructions for my newbie brain u would be my best (since i cant get what the instructions want me to do specifically)

Why are you in a hurry?
Do you really know how long it takes to make a DT for a device? It would be very simple if there was a tool that did everything automatically! But that's not how it works right now.

Maybe that's why you're anxious?!

Please, even if I write something, it is pre-preparatory to make it ready when the img file is good for everyone!

> ***for my newbie brain***

If you're really nervous and want something yesterday, then go tidy the house, sweep the yard, or do something else that's useful right now.
Have more patience!

**Comment by gaith-cr** [comment]
> > @lopestom from where i can get the boot_Tab10Pro_A11-20230908.img?
> > and the twarp u placed its link to a zip file and not (twarp).img
> > or maybe i just dont know how things work if is so tell me what i should do
> > if u can give me instructions for my newbie brain u would be my best (since i cant get what the instructions want me to do specifically)
> 
> Why are you in a hurry? Do you really know how long it takes to make a DT for a device? It would be very simple if there was a tool that did everything automatically! But that's not how it works right now.
> 
> Maybe that's why you're anxious?!
> 
> Please, even if I write something, it is pre-preparatory to make it ready when the img file is good for everyone!
> 
> > _**for my newbie brain**_
> 
> If you're really nervous and want something yesterday, then go tidy the house, sweep the yard, or do something else that's useful right now. Have more patience!

sheeeeeeeeesh man i got toasted by you i just dont how things workkkkkkkkk thats all
